"""empty message

Revision ID: 1fe92870b64f
Revises: 
Create Date: 2020-06-11 19:34:20.834310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe92870b64f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('transactions', sa.Column('time', sa.Time(), nullable=False))
    op.drop_index('ix_transactions_ref_id', table_name='transactions')
    op.create_unique_constraint(None, 'transactions', ['ref_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.create_index('ix_transactions_ref_id', 'transactions', ['ref_id'], unique=True)
    op.drop_column('transactions', 'time')
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
