"""empty message

Revision ID: 7b3f1d6450ff
Revises: 1b45960279a8
Create Date: 2020-06-18 10:47:22.740609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b3f1d6450ff'
down_revision = '1b45960279a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('regions', sa.Column('admin', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'regions', 'admins', ['admin'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regions', type_='foreignkey')
    op.drop_column('regions', 'admin')
    op.drop_table('admins')
    # ### end Alembic commands ###
