"""empty message

Revision ID: 95162cce000d
Revises: bb4848c6fdf2
Create Date: 2020-06-13 19:05:52.282653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95162cce000d'
down_revision = 'bb4848c6fdf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('token', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'token')
    # ### end Alembic commands ###
