"""empty message

Revision ID: bb4848c6fdf2
Revises: 3da0748a1195
Create Date: 2020-06-13 18:57:53.126098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4848c6fdf2'
down_revision = '3da0748a1195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('token', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'token')
    # ### end Alembic commands ###
