"""empty message

Revision ID: fcd803cf0bf9
Revises: b096dd3fbe06
Create Date: 2020-06-24 12:15:55.582946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcd803cf0bf9'
down_revision = 'b096dd3fbe06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    # ### end Alembic commands ###
